


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."company_generalInfo" (
    "id" integer DEFAULT 1 NOT NULL,
    "genetal_image_url" "text",
    "company_pdf_url" "text",
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "name" "text",
    "about_en" "text",
    "about_th" "text",
    "address_en" "text",
    "address_th" "text",
    "contact_email" "text",
    "contact_phone" "text",
    "facebook_url" "text",
    "instagram_url" "text",
    "youtube_url" "text",
    "line_url" "text",
    "logo_url" "text",
    "cover_url" "text"
);


ALTER TABLE "public"."company_generalInfo" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."production_gear" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "name_en" "text" NOT NULL,
    "name_th" "text" NOT NULL,
    "short_desc_en" "text",
    "short_desc_th" "text",
    "category" "text",
    "brand" "text",
    "model" "text",
    "image_url" "text",
    "available" boolean DEFAULT true
);


ALTER TABLE "public"."production_gear" OWNER TO "postgres";


ALTER TABLE "public"."production_gear" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."production_gear_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."production_works" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title_en" "text" NOT NULL,
    "title_th" "text" NOT NULL,
    "short_desc_en" "text",
    "short_desc_th" "text",
    "full_desc_en" "text",
    "full_desc_th" "text",
    "media_type" "text" NOT NULL,
    "media_url" "text",
    "thumbnail_url" "text",
    "category" "text",
    "featured" boolean DEFAULT false,
    "year" integer,
    "client" "text",
    "tags" "text"[]
);


ALTER TABLE "public"."production_works" OWNER TO "postgres";


ALTER TABLE "public"."production_works" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."production_works_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."software_projects" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "title_en" "text" NOT NULL,
    "short_desc_en" "text",
    "full_desc_en" "text",
    "target_en" "text",
    "features_en" "text",
    "title_th" "text" NOT NULL,
    "short_desc_th" "text",
    "full_desc_th" "text",
    "target_th" "text",
    "features_th" "text",
    "url" "text",
    "image_url" "text",
    "category" "text",
    "status" "text" DEFAULT 'Active'::"text",
    "version" "text",
    "featured_slot" smallint
);


ALTER TABLE "public"."software_projects" OWNER TO "postgres";


ALTER TABLE "public"."software_projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."software_projects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."company_generalInfo"
    ADD CONSTRAINT "company_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."production_gear"
    ADD CONSTRAINT "production_gear_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."production_works"
    ADD CONSTRAINT "production_works_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."software_projects"
    ADD CONSTRAINT "software_projects_pkey" PRIMARY KEY ("id");



CREATE POLICY "Allow public read access" ON "public"."company_generalInfo" FOR SELECT USING (true);



CREATE POLICY "Enable Insert for authentication of user" ON "public"."company_generalInfo" FOR INSERT TO "authenticated" WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable Insert for authentication of user" ON "public"."production_gear" FOR INSERT TO "authenticated" WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable Insert for authentication of user" ON "public"."production_works" FOR INSERT WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable Insert for authentication of user." ON "public"."software_projects" FOR INSERT TO "authenticated" WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable delete for authenticated users only" ON "public"."production_works" FOR DELETE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable delete for authenticated users only" ON "public"."software_projects" FOR DELETE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable delete for authenticated users only." ON "public"."company_generalInfo" FOR DELETE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable delete for authenticated users only." ON "public"."production_gear" FOR DELETE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."company_generalInfo" FOR UPDATE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."production_gear" FOR UPDATE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."production_works" FOR UPDATE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable update for authenticated users only" ON "public"."software_projects" FOR UPDATE TO "authenticated" USING (("auth"."role"() = 'authenticated'::"text")) WITH CHECK (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Public items are viewable by everyone" ON "public"."software_projects" FOR SELECT USING (true);



CREATE POLICY "Public read gear" ON "public"."production_gear" FOR SELECT USING (true);



CREATE POLICY "Public read works" ON "public"."production_works" FOR SELECT USING (true);



ALTER TABLE "public"."company_generalInfo" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."production_gear" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."production_works" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."software_projects" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."company_generalInfo" TO "anon";
GRANT ALL ON TABLE "public"."company_generalInfo" TO "authenticated";
GRANT ALL ON TABLE "public"."company_generalInfo" TO "service_role";



GRANT ALL ON TABLE "public"."production_gear" TO "anon";
GRANT ALL ON TABLE "public"."production_gear" TO "authenticated";
GRANT ALL ON TABLE "public"."production_gear" TO "service_role";



GRANT ALL ON SEQUENCE "public"."production_gear_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."production_gear_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."production_gear_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."production_works" TO "anon";
GRANT ALL ON TABLE "public"."production_works" TO "authenticated";
GRANT ALL ON TABLE "public"."production_works" TO "service_role";



GRANT ALL ON SEQUENCE "public"."production_works_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."production_works_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."production_works_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."software_projects" TO "anon";
GRANT ALL ON TABLE "public"."software_projects" TO "authenticated";
GRANT ALL ON TABLE "public"."software_projects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."software_projects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."software_projects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."software_projects_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































